apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    nodePort: 30181
    protocol: TCP
  selector:
    app: zookeeper
  type: NodePort